const jobs = [
  {
    id: "j1",
    title: "Web Designer",
    posted: "1 Day",
    posted_at : "20 JULY 2021",
    deadline : "20 AUGUST 2021",
    experience : "2 Years",
    education:"Bachelor Degree",
    english : "Professional",
    japanese : "Professional",
    location: "Tokyo, Japan",
    employment : "Full-time",
    salary: "600.000 JPY",
    skills: ["ReactJS", "ExpressJS",  "VueJS", "JavaScript","User Interface" , "User Testing"],
    description:
      "Own the end-to-end design process, from research to beautiful UI design through to shipping code.",
    company: "Fintech Company",
    overview:
      "This brand is an innovative and fast-growing global provider of gym software. They are dedicated to a vision of motivating, educating and inspiring individuals to a healthier lifestyle through the use of their “member-centric” fitness software. They are currently recruiting a Customer Support Agent to join their team in Tokyo and help deliver and maintain excellent customer service as they expand.",
    detail: "Customer experience is at the heart of what we do, and in line with our company values we want to ensure our customers always feel valued and supported. You will be responsible for replying to customer queries, investigating problems, and escalating queries through the correct channels where appropriate. Ensuring the more complex client issues are followed up and resolved in a timely manner is key, therefore you must have the ability to work under pressure, stay organized, and have a drive for action and outcomes.",
    responsibility: [
        "Your key responsibilities will be:",
      "Managing the support system by responding to online ticket requests",
      "Ensure support SLA's are met",
      "Escalating scenarios of required",
      "Working with customers to gather information",
      "Investigate and test scenarios on the product",
      "Offer guidance on using product, via phone or email",
    ],
    qualification: [
      "At least 5-year experience working with medium-large digital applications",
      "Demonstrable track record of achievements with a solid portfolio",
      "Proficient in Sketch, Figma, Abstract, Framer X and Invision/Marvel",
      "Basic understanding in HTML-CSS",
      "Basic understanding of React or similar modern JS frameworks",
      "Data-driven DNA",
      "Agile methodologies",
      "Problem solving oriented",
      "Good communication skills",
    ],
  },
  {
    id: "j2",
    title: "Web Designer",
    posted: "17 Days",
    location: "Tokyo, Japan",
    employment: "Full-time",
    salary: "600.000 JPY",
    skills: ["ReactJS", "ExpressJS", "JavaScript", "HTML", "CSS"],
    description:
      "Own the end-to-end design process, from research to beautiful UI design through to shipping code.",
  },
  {
    id: "j3",
    title: "Web Designer",
    posted: "1 Month",
    location: "Tokyo, Japan",
    employment: "Full-time",
    salary: "600.000 JPY",
    skills: ["ReactJS", "ExpressJS", "JavaScript", "HTML", "CSS"],
    description:
      "Own the end-to-end design process, from research to beautiful UI design through to shipping code.",
  },
  {
    id: "j4",
    title: "Web Designer",
    posted: "1 Day",
    location: "Tokyo, Japan",
    employment: "Full-time",
    salary: "600.000 JPY",
    skills: ["ReactJS", "ExpressJS", "JavaScript", "HTML", "CSS"],
    description:
      "Own the end-to-end design process, from research to beautiful UI design through to shipping code.",
  },
  {
    id: "j5",
    title: "Web Designer",
    posted: "1 Day",
    location: "Tokyo, Japan",
    employment: "Full-time",
    salary: "600.000 JPY",
    skills: ["ReactJS", "ExpressJS", "JavaScript", "HTML", "CSS"],
    description:
      "Own the end-to-end design process, from research to beautiful UI design through to shipping code.",
  },
  {
    id: "j6",
    title: "Web Designer",
    posted: "1 Day",
    location: "Tokyo, Japan",
    employment: "Full-time",
    salary: "600.000 JPY",
    skills: ["ReactJS", "ExpressJS", "JavaScript", "HTML", "CSS"],
    description:
      "Own the end-to-end design process, from research to beautiful UI design through to shipping code.",
  },
  {
    id: "j7",
    title: "Web Designer",
    posted: "1 Day",
    location: "Tokyo, Japan",
    employment: "Full-time",
    salary: "600.000 JPY",
    skills: ["ReactJS", "ExpressJS", "JavaScript", "HTML", "CSS"],
    description:
      "Own the end-to-end design process, from research to beautiful UI design through to shipping code.",
  },
  {
    id: "j8",
    title: "Web Designer",
    posted: "1 Day",
    location: "Tokyo, Japan",
    employment: "Full-time",
    salary: "600.000 JPY",
    skills: ["ReactJS", "ExpressJS", "JavaScript", "HTML", "CSS"],
    description:
      "Own the end-to-end design process, from research to beautiful UI design through to shipping code.",
  },
  {
    id: "j9",
    title: "Web Designer",
    posted: "1 Day",
    location: "Tokyo, Japan",
    employment: "Full-time",
    salary: "600.000 JPY",
    skills: ["ReactJS", "ExpressJS", "JavaScript", "HTML", "CSS"],
    description:
      "Own the end-to-end design process, from research to beautiful UI design through to shipping code.",
  },
  {
    id: "j10",
    title: "Web Designer",
    posted: "1 Day",
    location: "Tokyo, Japan",
    employment: "Full-time",
    salary: "600.000 JPY",
    skills: ["ReactJS", "ExpressJS", "JavaScript", "HTML", "CSS"],
    description:
      "Own the end-to-end design process, from research to beautiful UI design through to shipping code.",
  },
];

export default { jobs };
